# Generated by Django 4.2.5 on 2023-10-18 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('personName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30)),
                ('cusAddress', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('dateOrdered', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('personName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30)),
                ('license_plate', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_address', models.CharField(max_length=256)),
                ('shop_phone', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('totalAmount', models.DecimalField(decimal_places=5, max_digits=50)),
                ('success', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.order')),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=200)),
                ('pro_description', models.TextField()),
                ('quantityInStocks', models.IntegerField()),
                ('buyPrice', models.DecimalField(decimal_places=5, max_digits=50)),
                ('sellPrice', models.DecimalField(decimal_places=5, max_digits=50)),
                ('manufacturing_date', models.DateTimeField(auto_now_add=True)),
                ('sup_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.category')),
                ('supplierShop', models.ManyToManyField(to='classicmodels.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='orderDetails',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.SmallIntegerField()),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.supplement')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='classicmodels.orderdetails'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.shipper'),
        ),
        migrations.CreateModel(
            name='credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=200)),
                ('pro_description', models.TextField()),
                ('quantityInStocks', models.IntegerField()),
                ('buyPrice', models.DecimalField(decimal_places=5, max_digits=50)),
                ('sellPrice', models.DecimalField(decimal_places=5, max_digits=50)),
                ('manufacturing_date', models.DateTimeField(auto_now_add=True)),
                ('clt_size', models.CharField(max_length=32)),
                ('clt_color', models.CharField(max_length=32)),
                ('clt_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.category')),
                ('supplierShop', models.ManyToManyField(to='classicmodels.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=200)),
                ('pro_description', models.TextField()),
                ('quantityInStocks', models.IntegerField()),
                ('buyPrice', models.DecimalField(decimal_places=5, max_digits=50)),
                ('sellPrice', models.DecimalField(decimal_places=5, max_digits=50)),
                ('manufacturing_date', models.DateTimeField(auto_now_add=True)),
                ('acc_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.category')),
                ('supplierShop', models.ManyToManyField(to='classicmodels.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
