# Generated by Django 4.2.5 on 2023-10-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=200)),
                ('pro_description', models.TextField()),
                ('quantityInStocks', models.IntegerField()),
                ('buyPrice', models.DecimalField(decimal_places=5, max_digits=50)),
                ('sellPrice', models.DecimalField(decimal_places=5, max_digits=50)),
                ('manufacturing_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='clt_cat',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='supplierShop',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='sup_cat',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supplierShop',
        ),
        migrations.AddField(
            model_name='credit',
            name='creditNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postCode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shipper',
            name='postCode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='workplace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='credit',
            table='Credit',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='orderdetails',
            table='OrderDetails',
        ),
        migrations.AlterModelTable(
            name='shipper',
            table='Shipper',
        ),
        migrations.AlterModelTable(
            name='shop',
            table='Shop',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='Transaction',
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.AddField(
            model_name='product',
            name='product_cat',
            field=models.ManyToManyField(to='classicmodels.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplierShop',
            field=models.ManyToManyField(to='classicmodels.shop'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.product'),
        ),
        migrations.DeleteModel(
            name='Supplement',
        ),
    ]
