# Generated by Django 4.2.5 on 2023-10-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0002_product_remove_clothes_clt_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='id',
        ),
        migrations.AlterField(
            model_name='credit',
            name='creditNumber',
            field=models.CharField(blank=True, default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
