# Generated by Django 4.2.5 on 2023-10-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0003_remove_credit_id_alter_credit_creditnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shopName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
