# Generated by Django 4.2.5 on 2023-10-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0004_shop_shopname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shopName',
            field=models.CharField(max_length=30),
        ),
    ]
