# Generated by Django 4.2.5 on 2023-10-24 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0007_alter_credit_owner_alter_transaction_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.customer'),
        ),
    ]
