# Generated by Django 4.2.5 on 2023-10-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0008_orderdetails_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='customer',
        ),
    ]
