# Generated by Django 4.2.5 on 2023-10-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0009_remove_orderdetails_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='amount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
