# Generated by Django 4.2.5 on 2023-10-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0011_alter_transaction_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='totalAmount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=50),
        ),
    ]
