# Generated by Django 4.2.5 on 2023-10-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0013_alter_credit_balance_alter_transaction_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentReceive',
            field=models.BooleanField(default=False),
        ),
    ]
