# Generated by Django 4.2.5 on 2023-11-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0015_order_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hasOrderedBefore',
            field=models.BooleanField(default=False),
        ),
    ]
