# Generated by Django 4.2.5 on 2023-11-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0016_customer_hasorderedbefore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='hasOrderedBefore',
        ),
    ]
