# Generated by Django 4.2.5 on 2023-11-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0017_remove_customer_hasorderedbefore'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalAmount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=50),
        ),
    ]
