# Generated by Django 4.2.5 on 2023-11-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0019_alter_order_dateordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipper',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='postCode',
        ),
    ]
