# Generated by Django 4.2.5 on 2023-11-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0020_remove_shipper_email_remove_shipper_postcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerreview',
            table='CustomerReview',
        ),
    ]
