# Generated by Django 4.2.5 on 2023-11-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0021_alter_customerreview_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
