# Generated by Django 4.2.5 on 2023-11-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0024_product_quantitysold'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippingAddress',
            field=models.CharField(choices=[("Haven't Ordered", "Haven't Ordered"), ('In Transit', 'In Transit'), ('Shipped', 'Shipped')], default="Haven't Ordered", max_length=50),
        ),
    ]
