# Generated by Django 4.2.5 on 2023-11-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0026_rename_shippingaddress_order_shippingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.customer'),
        ),
    ]
