# Generated by Django 4.2.5 on 2023-11-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0027_customerreview_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
