# Generated by Django 4.2.5 on 2023-11-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0028_transaction_paydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='afterSalePrice',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=50),
        ),
    ]
