# Generated by Django 4.2.6 on 2023-11-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0032_remove_order_am_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_quick_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
