# Generated by Django 4.2.6 on 2023-11-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0033_product_pro_info_product_pro_quick_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='afterSalePrice',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyPrice',
            field=models.DecimalField(decimal_places=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sellPrice',
            field=models.DecimalField(decimal_places=0, max_digits=50),
        ),
    ]
