# Generated by Django 4.2.6 on 2023-11-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0034_alter_product_aftersaleprice_alter_product_buyprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
    ]
