# Generated by Django 4.2.6 on 2023-11-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0035_alter_order_totalamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('titleImage', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('file', models.FileField(upload_to='blog/')),
                ('header', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=80)),
                ('written_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
    ]
