# Generated by Django 4.2.6 on 2023-11-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0037_alter_product_overallrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inFavList',
            field=models.CharField(choices=[('None', 'None'), ('No', 'No'), ('Yes', 'Yes')], default='None', max_length=20),
        ),
    ]
