# Generated by Django 4.2.6 on 2023-11-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0038_product_infavlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inFavList',
            field=models.BooleanField(default=False),
        ),
    ]
