# Generated by Django 4.2.6 on 2023-11-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0040_blogtag_blogpost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='totalAmount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=50),
        ),
    ]
