# Generated by Django 4.2.5 on 2024-05-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0042_customer_password_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
