# Generated by Django 4.2.5 on 2024-05-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0043_remove_customer_password_remove_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='', max_length=32),
        ),
    ]
