# Generated by Django 4.2.5 on 2024-05-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0044_customer_password_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.customer')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('favoriteList', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.favoritelist')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classicmodels.product')),
            ],
        ),
    ]
