# Generated by Django 4.2.5 on 2024-05-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0045_favoritelist_favoriteitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favoriteitem',
            table='FavoriteItem',
        ),
        migrations.AlterModelTable(
            name='favoritelist',
            table='FavoriteList',
        ),
    ]
