# Generated by Django 4.2.5 on 2024-05-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classicmodels', '0047_remove_product_infavlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
